<a href="https://colab.research.google.com/github/kk-shetty/data_science_ik/blob/main/assingments/maths_for_ml/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Q1. Write a Python function that takes a square matrix A as input and returns its eigenvalues and eigenvectors.

In [2]:
import numpy as np

In [3]:
def eigen(A):
    """Return Eigen Values and Eigen Vectors of a given Square matrix A
    """
    # Calculate eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eig(A)
    return eigenvalues, eigenvectors


In [4]:
matrix = np.array([[3,5,8],[2,4,1],[9,8,4]])

eigenvalues, eigenvectors = eigen(matrix)

print("Eigen Values:")
print(eigenvalues)

print("Eigen Vectors:")
print(eigenvectors)

Eigen Values:
[13.91645304 -4.85524621  1.93879316]
Eigen Vectors:
[[-0.63767173 -0.73849739  0.56317984]
 [-0.20352817  0.09135327 -0.73224369]
 [-0.74293408  0.66803906  0.38294602]]


#### Q2. Write a program which takes 2 arrays and returns the dot product without using NumPy

In [5]:
def dot_product(A,B):
    # Check if the arrays have the same length
    if len(A) != len(B):
        raise ValueError("Vectors must be of same dimension")

    result = sum(x * y for x, y in zip(A,B))

    return result

In [6]:
vec_a = np.array([2,4,6])
vec_b = np.array([1,7,2])

dot_prod = dot_product(vec_a, vec_b)

print(f"{vec_a} * {vec_b} is -> {dot_prod}")

[2 4 6] * [1 7 2] is -> 42


#### Q3. Write a Python function to calculate the determinant of a n by n matrix without using Python package

In [7]:
def minor(matrix, row_index, col_index):
    """Returns minor matrix at specified row and column index
    """
    # return np.delete(np.delete(matrix, row_index, axis=0), col_index, axis=1)
    return [[matrix[i][j] for j in range(len(matrix[i])) if j != col_index] for i in range(len(matrix)) if i != row_index]

In [8]:
def determinant(matrix):
    """Calculates and returns determinant of a matrix
    """

    if len(matrix) == 1:
        return matrix[0][0]

    det = 0
    for i in range(len(matrix)):
        # print(matrix[0,i])
        temp_det = (((-1)**(1+i+1)) * (matrix[0][i]) * (determinant(minor(matrix, 0, i))))
        # print(temp_det)
        det += temp_det

    return det


In [9]:
mat_a = np.array([[1,2,3],[4,5,6],[7,8,9]])
det_matrix =  determinant(matrix)
print(f"det({matrix}) = {det_matrix}")

det([[3 5 8]
 [2 4 1]
 [9 8 4]]) = -131


#### Q4. Write a Python function to calculate the rank of a matrix without using Python package

In [17]:
def max_pivot_row(matrix):
    """Returns the row number which has the max pivot eleement
    """

    max_value = float('-inf')
    max_row = -1

    for row_index in range(len(matrix)):
        if matrix[row_index, 0] > max_value:
            max_value = matrix[row_index, 0]
            max_row = row_index

    return max_row


In [41]:
def row_echelon(matrix):
    """Converts a given matrix into row echelon format
    """

    # Find the row number which has the highest left most number and swap it with first row
    max_pivot_row_num = max_pivot_row(matrix)
    matrix[0], matrix[max_pivot_row_num] = matrix[max_pivot_row_num].copy(), matrix[0].copy()

    pivot_index = -1
    for row_index in range(len(matrix)):
        col_index = 0
        while matrix[row_index, col_index] == 0:
            col_index += 1
        if col_index > pivot_index:
            pivot_index = col_index



    return matrix

In [42]:
mat_a = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat_a
row_echelon(mat_a)


array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])